(function(){"use strict";var __webpack_modules__={"./src/assets/css/index.scss":
/*!***********************************!*\
  !*** ./src/assets/css/index.scss ***!
  \***********************************/function(__unused_webpack_module,__webpack_exports__,__webpack_require__){eval("__webpack_require__.r(__webpack_exports__);\n// extracted by mini-css-extract-plugin\n\n\n//# sourceURL=webpack://webpack-study/./src/assets/css/index.scss?")},"./src/assets/js/public.js":
/*!*********************************!*\
  !*** ./src/assets/js/public.js ***!
  \*********************************/function(__unused_webpack_module,__webpack_exports__,__webpack_require__){eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export */ __webpack_require__.d(__webpack_exports__, {\n/* harmony export */   \"name\": function() { return /* binding */ name; }\n/* harmony export */ });\nfunction name(params) {\n  let p = params ?? 123\n  return 'liu' + p;\n}\n\n\n//# sourceURL=webpack://webpack-study/./src/assets/js/public.js?")},"./src/index.js":
/*!**********************!*\
  !*** ./src/index.js ***!
  \**********************/function(__unused_webpack_module,__webpack_exports__,__webpack_require__){eval('__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _assets_js_public__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./assets/js/public */ "./src/assets/js/public.js");\n/* harmony import */ var _assets_css_index_scss__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./assets/css/index.scss */ "./src/assets/css/index.scss");\n\n\nfunction showMsg() {\n  alert((0,_assets_js_public__WEBPACK_IMPORTED_MODULE_0__.name)())\n}\nwindow.showMsg = showMsg\n\n//# sourceURL=webpack://webpack-study/./src/index.js?')}},__webpack_module_cache__={};function __webpack_require__(_){var e=__webpack_module_cache__[_];if(void 0!==e)return e.exports;var s=__webpack_module_cache__[_]={exports:{}};return __webpack_modules__[_](s,s.exports,__webpack_require__),s.exports}__webpack_require__.d=function(_,e){for(var s in e)__webpack_require__.o(e,s)&&!__webpack_require__.o(_,s)&&Object.defineProperty(_,s,{enumerable:!0,get:e[s]})},__webpack_require__.o=function(_,e){return Object.prototype.hasOwnProperty.call(_,e)},__webpack_require__.r=function(_){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(_,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(_,"__esModule",{value:!0})};var __webpack_exports__=__webpack_require__("./src/index.js")})();